### ISSUE TITLE
Request: Forge port

### ISSUE THREAD

**Issue by vpontin** [bergerhealer/TrainCarts#103]
Hi all!

I know it would be a weird request, but given railcraft is still stuck on 1.7, is there any possibility to bring TrainCarts (with the very same features) into Forge 1.9.4/1.10.x?

It would be awesome since several mods and tools for Forge emulate part of Bukkit behaviour and features, so TrainCarts would close the bundle.

I have the idea to request this after a request and talks in MMD's discord channel.

**Comment by mg-1999** [comment]
This is only possible with a full rewrite and that is not gonna happen.

Sorry.

**Comment by vpontin** [comment]
sorry the necro, but if a modder became interested in doing the dirty work, can he have authorization to do that?

**Comment by FriwiDev** [comment]
Of course :)

**Comment by liach** [comment]
@vpontin Railcraft is available on MC 1.10.2 already, although it is buggy. A Sponge port would be worthy.

**Comment by vpontin** [comment]
I know, this is my major issue with Railcraft (the number of bugs), but i dont use Sponge too, because i play mostly on singleplayer. Thats why i requested a direct port for forge

**Comment by liach** [comment]
@vpontin You can use Sponge plugins by installing SpongeForge and Sponge plugins like how you install other Forge mods. This works on SinglePlayer.

**Comment by bergerkiller** [comment]
I will consider figuring out support for Minecraft forge in a future release, but not for the current release as I'm trying to roll out a stable version. For forge support I will need to start digging into Mountiplex to add remapping hooks, so it has a bit of a stability risk I dont want to take just yet.

**Comment by vpontin** [comment]
Ohhh i hope i will live to see this fabulous plugin released to Forge! Thanks a lot @bergerkiller !!

**Comment by bergerkiller** [comment]
Even so, I think Forge could be supported, even outside cauldron/thermos, considering I have a fully capable remapping system in the plugin already. Only thing I don't know is how the Bukkit bindings work on bare Forge 1.8+.

**Comment by liach** [comment]
@bergerkiller I suggest you to switch to mcp mapping. Spigot mappings are largely obfuscated, while mcp mappings have extra javadocs and detailed field names (if you think a name is bad, you can even open issues to request changes)

**Comment by liach** [comment]
In Minecraft 1.8+, there is no stable implementation that brings bukkit or spigot upon forge.

**Comment by bergerkiller** [comment]
Well there's an awful lot of use of Bukkit API from simple things like Vector to org.bukkit.Entity. I kind of need those. Sure, I can make an entire proxy api and ditch all of Bukkit, but it stops being a bukkit plugin by then. Is there really no plugin or project that at least tries to provide the bukkit api?

**Comment by vpontin** [comment]
Like @liach said, sadly after 1.8+ no one wanted anymore to update Cauldron/Thermos to these versions, mostly because after the Bukkit drama the devs created Sponge. But i prefer to use native forge mods instead, because Sponge is far from being stable, i mostly use singleplayer (aka 'local multiplayer' according to Minecraft standard) and in multiplayer occasions i dont have much resources on the server machine to attach yet another API to bother with.

And seems like a "port" for Forge would be a full rewrite, so it would be a hard challenge to do. Sorry.

**Comment by bergerkiller** [comment]
Its a full rewrite, but dont forget that forge still uses the NMS source. The only difference is that the remappings and class paths differ. The biggest challenge is more so that BKCommonLib on the outside exposes Bukkit classes like Entity, Block, Material and so forth. When those aren't there, BKCommonLib has no API to expose.

I can quite easily implement my own types in BKCommonLib (I already did with BlockData and CommonEntity API), but it would be a full rewrite in some respects yes. But most in BKCommonLib relies on net.minecraft.server, and not Bukkit or CraftBukkit, so not all hope is lost there.

**Comment by liach** [comment]
Forge alters vanilla in a way that mods can work. It should not be too bad (it removes some identity checking for types so that mod custom items can extend vanilla). It does not remove too many vanilla features (however, it removed vanilla entity registry in favor of its own one)

@vpontin In fact, you can run sponge forge on your minecraft singleplayer game (sounds unbelievable, but it is the case)

Forge does not support many of the bukkit apis. Bukkit apis assume that mods would not present, so there is some hardcoded type checking.

**Comment by bergerkiller** [comment]
Most complexity comes from replacing network and entity logic completely. I don't know if Sponge allows this. Forge may actually be easier because of that; because it still has the backing nms code in some form.

About the only thing putting this on halt right now is that there is no support for Bukkit API. Without the bukkit events and most importantly, bukkit types like Entity and Block, most of the plugin <> BKCommonLib interface simply cannot function. I don't have a good solution for this at this time.

**Comment by vpontin** [comment]
Like i thought: Only a rewrite could be successful due to the numerous differences in the APIs. In addition, Bukkit API is extremely problematic legal-wise (because of the infamous DCMA) to be incorporated into the Forge.
Well, thats is. But i need to thank a lot @bergerkiller due to, at least, think about bring TrainCarts for 1.12+. Most modders i talked about this rejected the request at first glance ("USE RAILCRAFT" was the main excuse).

**Comment by liach** [comment]
so no forge/sponge port?
