### ISSUE TITLE
Detector sign labels

### ISSUE THREAD

**Issue by MinePlayer64** [bergerhealer/TrainCarts#114]
##### Spigot version:
CraftBukkit version git-Spigot-54ec0b8-e17c3d2 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

<hr>

Sometimes you need overlapping detector regions.
This is currently not easy or not even possible to do.

Detector signs should be able to have labels.
Only signs with the same label should create a detector region.

Possible format:
```
[+train]
detector:asdf
empty

```

It might be a good idea to add a shorter alias for the detector sign (det?) so you can use longer labels.

**Comment by bergerkiller** [comment]
I think it's a good idea to add this, yeah. Will merge it tomorrow when I have the code open, got to make sure there is no other logic in the detector right now that could interfere. Otherwise, seems all good to me.

**Comment by bergerkiller** [comment]
I have merged your commit and made some minor changes myself. Code was getting stale. I have added your functionality, with in addition it working with both _detector:label_ and _detector label_ 

Did that because other signs work with a space separator too, don't want it to be confusing.

https://github.com/bergerhealer/TrainCarts/commit/f04f61e2dc17861b087b2600c03bb559ec9f507b
