### ISSUE TITLE
item_break effect crashes nearby players

### ISSUE THREAD

**Issue by MinePlayer64** [bergerhealer/TrainCarts#124]
##### Spigot version: `git-Spigot-3fb9445-fecf4b4 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)`

<hr>

#### Problem or bug:
Playing the `item-break` effect will disconnect nearby players.
This can be used to prevent players from playing.

#### Expected behaviour:
Nothing should happen.

#### Steps to reproduce:
```
[train]
effect
item_break

```
Supply a redstone signal to that sign.

<hr>

This probably happens because the item_break effect needs a data value so it knows which item broke.
The best solution probably is blacklisting that effect.

**Comment by bergerkiller** [comment]
b33a592

Fixed the issue due to missing material information. There is no easy way to fix it proper, because ITEM_BREAK/BLOCK_BREAK is in reality 2/3 effects: sound of being hit/broken, particle of slapping the block (optional), the block actually breaking. When the TC effect API was written, it was meant for just the Effect enum in Bukkit, with Sound hastily added. Now there is also Particle, with loads of parameter options, and this requires a much more versatile API. A sign isn't the way to go here. I'll have to consider a more graphical way to do this, perhaps the map API can have a moment to shine.
