### ISSUE TITLE
Carts cannot be destory by one hit in creative mode

### ISSUE THREAD

**Issue by david50407** [bergerhealer/TrainCarts#137]
##### Spigot version: 1.11.2-R0.1-SNAPSHOT (git-Spigot-283de8b)

<hr>

#### Steps to reproduce: 

1. Place a cart

2. Hit cart in creative mode until it drop a cart item

I don't know if this is TrainCarts feature or not. But in original game, carts should be destroyed by only one hit in creative mode and won't drop cart item.

**Comment by bergerkiller** [comment]
The original reason that you can not instantly destroy minecarts in creative is that the 'slapping' action doubles as a means to select the minecart. The last train slapped can be altered with commands to set properties or to /train destroy it. Its why I always have a diamond sword with me now in my inventory, so I understand the frustration it causes. I will make it so that when you crouch as a player in creative, it will destroy the minecart in one hit.

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/623c0b1304b31d12b9329ef5bd106682ac5ee1b6

Note: if you ran TC before, you will have to change "instantCreativeDestroy" to _true_ in the config.yml. It was defaulted to false before. You can then destroy minecarts instantly, they will not drop minecarts and you can still select them by sneaking and then clicking.

https://ci.mg-dev.eu/job/TrainCarts/46/

**Comment by david50407** [comment]
Works well! thanks again 😄
