### ISSUE TITLE
Weird behavior on station caused train get out of rails

### ISSUE THREAD

**Issue by david50407** [bergerhealer/TrainCarts#147]
##### Spigot version: 1.12

<hr>

#### Problem or bug:

In some case, Station will cause cart exit the rails. See the youtube link below:

https://youtu.be/JEMSXYwzW-0

#### Expected behaviour:

Cart won't exit rails.

#### Steps to reproduce:

See the video above, if I turn the direction of rails immediately, cart will exit the rails.
This seems only happend on Station, Launch doesn't have this issue.

**Comment by bergerkiller** [comment]
Can reproduce on latest version, though the bug test case is very specific. I'll see what I can do.

**Comment by bergerkiller** [comment]
Bug was caused by an incorrect maxspeed being set. In detail, when the minecart is moving at <0.4 blocks/tick it sets the maxspeed to whatever is set as speed limit, in this case, 0.6. When the minecart velocity reaches >0.4 inside the physics function (due to a launch) then it derails, because the minecart is moved to beyond the block attached to the curve.
https://github.com/bergerhealer/TrainCarts/commit/5f05bc2b7d4bf1ad74af5f33ce403d63532c5ec9

https://ci.mg-dev.eu/job/TrainCarts/72/
