### ISSUE TITLE
Disable viewing self while on vertical rails

### ISSUE THREAD

**Issue by Legobuilder0813** [bergerhealer/TrainCarts#180]
##### Spigot version: 1.12.2-R0.1-SNAPSHOT (git-Spigot-549c1fa-45c8386, latest as of writing this)

<hr>

**Comment by bergerkiller** [comment]
Are you using upside-down rails? It should only be changing the scoreboard when switching between upside-down and upright. In other cases no scoreboard (well, player info-) should be sent.

Even then, yeah I think this can be turned on/off so that it won't mess with the scoreboard. I can keep the 3rd perspective view though, because that doesn't depend on the scoreboard/playerinfo refreshing logic. I can make that also be toggleable, however for vertical rails it causes players to appear inside the block above and it is no option.

How exactly does it mess up the builds? I can make an extra configurable option for whether or not third person view is activated on vertical rails.

**Comment by Legobuilder0813** [comment]
Sorry for the confusion (I don't know if what I said made sense but I confused myself lol). I'm not using upside down rails, players are being moved into the 3rd perspective when going into any vertical segment. We don't use upside down rails so if you could add a toggle for 3rd person view on vertical rails that'd be great 👍 
![2017-12-21_17 28 54](https://user-images.githubusercontent.com/6166238/34277887-a5789e3a-e675-11e7-9d9f-4bc6ba140295.png)
![2017-12-21_17 29 04](https://user-images.githubusercontent.com/6166238/34277888-a583c882-e675-11e7-8105-cc331da9fa16.png)
![2017-12-21_17 29 07](https://user-images.githubusercontent.com/6166238/34277889-a5953ae0-e675-11e7-8eec-a3e98227bf4a.png)
![2017-12-21_17 29 10](https://user-images.githubusercontent.com/6166238/34277890-a59f38ba-e675-11e7-8454-6d615581ba40.png)
![2017-12-21_17 29 13](https://user-images.githubusercontent.com/6166238/34277891-a5a9b95c-e675-11e7-84ff-d873f3e24e74.png)
![2017-12-21_17 29 15](https://user-images.githubusercontent.com/6166238/34277892-a5b3c2a8-e675-11e7-89e5-ba5538a54280.png)

**Comment by bergerkiller** [comment]
It is technically where the head is at though when at that angle. There is just no way to pitch the player so that the feet are in the right place. I do wonder how come you can see the invisible player, though? Is that a mod?

**Comment by Legobuilder0813** [comment]
That was what I saw in F5, my best guess for the ghost is because of a scoreboard I have setup on my server the player sees friendly invisibles and in this case that means myself.

Could you still add that option though? I agree it's where the head would normally be if the player is tilted forward and sitting upwards, but for us it works better for the perspective to remain the same.

**Comment by bergerkiller** [comment]
I can see what I can do

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/TrainCarts/208/

Set 'enableSeatThirdPersonView' to false in the config.yml, and it will not change camera angles on vertical rails. If you need this setting per train instead of global, that can be arranged too.
