### ISSUE TITLE
Carts changed to mountable entities with Attachment Editor not behaving as expected

### ISSUE THREAD

**Issue by bc-hill** [bergerhealer/TrainCarts#196]
##### Spigot version: 1.12.2

<hr>

#### Problem or bug:
Players attempting to ride certain carts perceive their motion as having stopped, while other players see them continue to move normally.  To the rider, the cart may also appear to leave the tracks.
Pigs seem to be the exception.

#### Expected behaviour:
Cart should behave like a cart.

#### Steps to reproduce:

1. Create cart or train
2. Select first option in attachment editor
3. On next screen, change second line to an entity that is normally mountable in Minecraft (Horse, zombie horse, boat, etc.)
4. Attempt to ride the cart or train.

**Comment by bergerkiller** [comment]
As a workaround, try repositioning the seat so that players dont actually ride the entities themselves. I suspect players might be doing a weird kind of movement prediction, at least for horses.

**Comment by bc-hill** [comment]
Thank you, I can confirm that changing the riders Y position allows for more natural movement.  That makes sense, that the client would try to take over some of that.  Could you maybe have it automatically add a slight offset when when using one of those entities?

Though the ride is smooth, the carts still do not behave properly as a member of a train.  See attached, and thank you!

![image](https://user-images.githubusercontent.com/7044511/35389289-f5cd8c8e-018b-11e8-9a71-89cf5c1740c2.png)

**Comment by bergerkiller** [comment]
That too is unfortunately all client-sided problems. Minecraft does a bunch of strange movement predictions/smoothening, and it causes some entities to lag behind or go faster than others. For example, armor stands will always move a bit ahead of minecarts, and boats are probably the slowest of them all. When the train comes to a stop, youll see all entities move back in proper position.

In the past I attempted working around it by doing movement prediction myself on the server, and sending position updates further ahead than it really is. This is a way to at least minimize the glitches, but the problem is that [there is no documentation on this to be found whatsoever](https://www.spigotmc.org/threads/entity-network-synchronization-and-their-woes.279502/#post-2714432). Believe me, I searched :(

I think it is a good idea to automatically put players (first-person) at an offset if they are at risk of taking over movement. This applies to boats for sure, I didn't know it also happened with other mobs like chickens though. Funny how pig is an exemption. Typical minecraft...
