### ISSUE TITLE
Dismounting from elevated train moves player to height of track

### ISSUE THREAD

**Issue by bc-hill** [bergerhealer/TrainCarts#199]
##### Spigot version: 1.12.2

<hr>

#### Problem or bug:
Dismounting from elevated train moves player to height of track

#### Expected behaviour:
Player should dismount at height of the cart that they are exiting

#### Steps to reproduce:
1. Create minecart on track
2. Using attachment editor, raise Y coordinate to +2.25
3. Place platform of blocks to where they are between cart and track
4. Ride minecart
5. Dismount
You will now be under the block platform, instead of standing on it.

![image](https://user-images.githubusercontent.com/7044511/35491313-9da91060-045a-11e8-8762-a2042af71d74.png)

**Comment by bergerkiller** [comment]
You can set a different exit offset for trains by changing the exit offset. Can be done using property signs or by through commands, or setting it in DefaultTrainProperties.

Attachments currently have no effect on where players exit (because attachments are purely visual candy). I'll take this as that players should exit relative to the seat position theyre in, which can be arranged.
