### ISSUE TITLE
3D Models Paper

### ISSUE THREAD

**Issue by Tommetjuhhhh** [bergerhealer/TrainCarts#209]
##### Spigot version: 1.12.2.-R0.1

Goedendag!

Wij gebruiken al jaren TrainCarts en wat een heerlijke plug-in is het! Echter heb ik wel een vraagje omtrent het '3D Model'. Het papieren menu dat je krijgt om de rit aan te passen werkt niet echt geweldig.
Wanneer wij /train attachments doen, krijg je vervolgens een paper in je inventaris. Maar wanneer je deze opent zie je een map in plaats van het menu dat jullie gemaakt hebben.

Ik weet niet of dit probleem al bekent is of misschien ben ik wel de enige. Ik zou het zeker waarderen als u op mijn bericht reageert. Is dit op te lossen? Ik hoor graag van u!

Groetjes,
Tom

**Comment by Tommetjuhhhh** [comment]
I have assumed that BergerHealer speaks Dutch. If this is not the case, I will translate my message to English! Fine evening already.

**Comment by bergerkiller** [comment]
Yes I'm a dutchie, this time I'll _see it through the fingers_ ;)

I'm not sure why it doesn't show a proper map for you. In any case, that looks like a bug to do with the server software you are using not being compatible with the map API in BKCommonLib. This can be due to errors (check the server log for anything!) or perhaps that it fails to listen / modify map packets and item inventory refreshes to show the correct map.

Have you installed protocollib or not? It may be required on your server because of a plugin conflict of a sort if it is not installed.

**Comment by Tommetjuhhhh** [comment]
Thanks for your reply! We have in the server indeed ProtocolLib v 4.3.0 sit. In The logs I did find the following HTTPS://PASTEBIN.COM/QR8WRAPD

**Comment by bergerkiller** [comment]
> java.lang.UnsupportedOperationException: Field net.minecraft.server.ItemStack.tagField is not available

Yeps thats a bug that has been fixed (or at least attempted to be fixed) in the development build of BKCommonLib. Does it still show with the dev-build?

**Comment by Tommetjuhhhh** [comment]
Hi! Yes, it works! and without error messages. Super Thanks! If I have any questions or if something works then I'll bother you again haha! Fine evening.

**Comment by bergerkiller** [comment]
Glad it worked, have a good day :)
