### ISSUE TITLE
TrainCarts induce lag to server (TPS drop)

### ISSUE THREAD

**Issue by RichVillage** [bergerhealer/TrainCarts#234]
##### Spigot version:  1.13.1-R0.1-SNAPSHOT

<hr>

#### Problem or bug: TrainCarts makes too much lag (Train Physics)
Please check this timings data: https://timings.spigotmc.org/?url=wipacowude

#### Steps to reproduce: N/A

Because of Train Carts, TPS is dropping to 20 -> 4.xx.. Please fix this..

**Comment by male-gal** [comment]
"Steps to reproduce: N/A" => that helps so much.

**Comment by bergerkiller** [comment]
Firstly, disable block collision for trains that dont need them to improve the timings of onMove.

Next, theres a lot of time spent in updateChunkInformation, which means its loading a lot of chunks sync instead of async. Theres been a bunch of trouble loading chunks asynchronously, and it might not yet work correctly, so that is an issue point worth looking into still.

Is this on the latest dev build of BKCommonLib from the jenkins ci? (I assume yes)

**Comment by RichVillage** [comment]
@male-gal It happens randomly not happens when I was doing something specially. So I don't know how to reproduce this problem...

**Comment by RichVillage** [comment]
@bergerkiller Thank you for replying, but as you know, the problem was fixed thanks to your hard work!
My nickname is Lavender in TC Discord channel.. Thank you again for your hard work for me..

**Comment by bergerkiller** [comment]
@RichVillage I recognized your icon but I thought it might've been a new issue :)

I'll close this issue, then.
