### ISSUE TITLE
Expand API capabilities

### ISSUE THREAD

**Issue by marnixbent** [bergerhealer/TrainCarts#235]
##### Spigot version:

<hr>

#### Problem or bug:
We want to replace our redstone systems with Java plugins and would love to see more API functionalities. We still make use of the signs, but want to interact with those signs through Java code.
- Spawn a train
- Toggle player enter and exit for a train (on a specific station)
- Start a train by releasing a station
- Control switches
- Detecting trains

**Comment by bergerkiller** [comment]
Since traincarts is already Java code, you can already do all these things. Some will be harder to achieve than others, though. I'll go by these one by one.

> Spawn a train
First you use a walk iterator to compute all the positions in the world to spawn the train at. Then you spawn the train using MinecartGroupStore.spawn, where you can also specify the types. This logic is kind of difficult to understand, so some improvement to make this easier to use would be nice.

> Toggle player enter and exit for a train (on a specific station)
Each train is a MinecartGroup and has properties obtained using getProperties(). These can be modified at will.

> Start a train by releasing a station
What does 'start' mean here? If you need a lot of extra functionality tied to a station sign, I can instead recommend to implement your own kind of SignAction and register it using SignAction.register(myAction). You can extend SignActionStation and add your own things to it, but name it 'exstation' instead. [LINK_A](https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/signactions/SignAction.java#L86) and [LINK_B](https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/signactions/SignActionStation.java)

> Control switches
To control rails, you will need to know the rails block. You can then use the newly introduced Junction API to control the switching of the rails. This is, however, much easier to do when handling using a SignAction, because it computes the 'from' junction for you. [LINK](https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/events/SignActionEvent.java#L381)

If you want to start with your own API into traincarts, I can strongly recommend starting with a custom SignAction to do things in. The execute handler gives you a SignActionEvent, with all the metadata you could ever need. (rails, sign, redstone power, trains, etc). Look at how the Station sign action was implemented, and maybe also peek at the other sign actions.

If there is an aspect that is really difficult to use from Java right now, I can accommodate it with some better methods. I'll need very specific details though. In terms of what is or isn't possible, everything is, the API isn't limited in any way.

**Comment by harm27** [comment]
@bergenkiller since i am the one that is gonna code it for @marnixbent, i will explain something in more detail.

Spawning a train: 
So when i know the coordinates for the spawn sign, then i could spawn a train?
Does it also work with the addons tccoasters and tchangrail?

Toggleing player enter and exit is clear now.

Starting from station:
What we ment is changing the state for a station sign. First so that the train stops and on a later moment change it so that the train departs. So is that possible and how?

**Comment by bergerkiller** [comment]
> So when i know the coordinates for the spawn sign, then i could spawn a train?
> Does it also work with the addons tccoasters and tchangrail?

Yes. In fact, you can use an actual spawn sign with this, and retrieve the full spawn sign metadata including a spawn() method to do all this logic.
```
Block spawnSignBlock = ...; // up to you
SignActionEvent spawnSignEvent = new SignActionEvent(spawnSignBlock);
SpawnSign spawnSign = TrainCarts.plugin.getSpawnSignManager().create(spawnSignEvent); // get or create
spawnSign.spawn();
```

As for the station, it doesn't have to be a station to do these things. The station wraps around the action api (group.getActions()) where new launch actions / wait actions can be scheduled. All the logic for dealing with a station sign is wrapped around the [Station class](https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/Station.java), which you can create yourself with the parameters needed.

What you really want is part of the logic of Station, with a little extra logic to automatically depart. All of this is best handled using Actions, which are little tasks running every tick until they return true. https://github.com/bergerhealer/TrainCarts/tree/master/src/main/java/com/bergerkiller/bukkit/tc/actions

Make your own action, do your logic in there every tick. Then add all the actions in the sequence they should execute when handling your custom SignAction group enter. For example, a common pattern:

1. MemberActionLaunch to center the train above the sign. The Station class has some clever logic here to compute the distance to launch to center exactly, re-use that.
2. GroupActionWait / custom, to wait until the train can depart again. This you can implement yourself.
3. MemberActionLaunch to launch the train into the depart direction again

The station sign itself is an abstraction for all these actions. You don't need a station sign for the same behavior to be re-created.

**Comment by bergerkiller** [comment]
> So that a custom waiter does not check on distance but on availability of a section.

Mutex zones are more likely a better option here, they are how that was meant to function.

> Another thing is keep a distance between trains without waiters. So if there is a train in x distance, then wait.

Already exists. That is the wait distance property which can be set per train.

**Comment by harm27** [comment]
Okay, will look into both.

**Comment by harm27** [comment]
Also @bergerkiller where can i find documentation or explaination about those mutex zones?

**Comment by bergerkiller** [comment]
https://minecraft.gamepedia.com/Custom_servers/Bukkit/TrainCarts/Signs/Mutex for the most part. This feature isn't properly implemented though, and lacks an API to define flexible regions. Its also limited to cuboid regions.

**Comment by harm27** [comment]
That could be a problem. Since sometimes sections cross with other sections.

**Comment by bergerkiller** [comment]
Mutexes are a problem by itself. The moment you have multiple overlapping mutexes, deadlocks become almost guaranteed. It works best when theres only one mutex zone to cover everything.

The plugin does not have sufficient mutex zoning logic to do what you want it to do. At the very least, non-cuboid zones must be possible first.

**Comment by harm27** [comment]
Is there another way of locking sections of a track? Like a new signaction linking signs and that way have the plugin somehow know where the trains are and if a section is free or not. I have some idea about it, but not how to proper implement it.

**Comment by harm27** [comment]
That is my primary case, so it would solve the issue for me. Can i also get to the detector sign and region from my code? Maybe with coordinates?

**Comment by bergerkiller** [comment]
Yes. If you know a single rails block that is part of a detector region (can obtain from a sign using SignActionEvent), they are in this registry.
https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/detector/DetectorRegion.java#L76
