### ISSUE TITLE
3d models

### ISSUE THREAD

**Issue by ShadowSkull20** [bergerhealer/TrainCarts#236]
<hr>

#### Problem: how can i add the 3d models I made with blockbench to the huge list of diamond swords in the attachments editor?

**Comment by bergerkiller** [comment]
Make a custom resource pack and upload it to a server. For testing, you can also upload to dropbox and use the download link for it (change dl=0 to dl=1). Put this link in server.properties, restart the server and now clients will automatically download your resource pack (unless they disabled that). The attachment editor will also detect this server-installed resource pack and display the models in place.

Instead of putting it in server.properties, you can also set 'resourcePack' in config.yml of Traincarts to either the download URL or a filesystem path where the resource pack can be found (.zip).

**Comment by ShadowSkull20** [comment]
I have a rp and know how to change blocks to my models but I need all blocks so I want to use diamond sword for all my models, you know when you edit a train and change it to Item, then the diamond sword en then you get a huge list of swords for different damages, I just can't figure how I can put  the first dia sw as my logflume, the 2nd CIA sw as my pop corn and so on

**Comment by bergerkiller** [comment]
If they are still not showing, that has to do with 'damaged'. In the JSON of the models, the predicate for damaged must be set to 0:
`"predicate": {"damaged": 0, "damage": 0.030303030303030304}`

**Comment by ShadowSkull20** [comment]
Ow they automatically go in the list? If not where did you get the damage number from?

**Comment by bergerkiller** [comment]
I feel a tutorial is more what you need. Some of these questions are better asked on the spigot forums. https://www.spigotmc.org/threads/tutorial-custom-item-models-in-1-9.134255/

In short, you need to assign damage values and set damaged to 0 for all the models in your resource pack. Often this is done automatically by what you use to export. Once this is done, and this resource pack is loaded server-side as well, you can cycle through them in the UI.

**Comment by ShadowSkull20** [comment]
Exactly what I was looking for thx
