### ISSUE TITLE
Minecarts getting caught on turns

### ISSUE THREAD

**Issue by MrWonka** [bergerhealer/TrainCarts#238]
##### Spigot version: 0.12.2-0.13.1

<hr>

#### Problem or bug:
Minecarts traveling at 0.4 or faster will suddenly stop on turns

**Comment by bbayu123** [comment]
Can you provide more information?

**Comment by MrWonka** [comment]
After further testing I've found it happens when legacy mode is enabled.

**Comment by bbayu123** [comment]
You mean legacySpeedLimiting?

**Comment by MrWonka** [comment]
Yes

**Comment by bergerkiller** [comment]
Haven't tested/used legacy speed limiting in a long while. I assume its allowing single-tick movement larger than 0.4 in that mode. I made note of this so I can look into it once I have time...

**Comment by bergerkiller** [comment]
I've fixed this issue: https://ci.mg-dev.eu/job/TrainCarts/410/

Commit: https://github.com/bergerhealer/TrainCarts/commit/526266fef106b22bb40ca415ceb96cec9b6ed2cc

Was due to a max movement limit which did not keep in mind that minecarts can move at sqrt(0.4*0.4+0.4*0.4+0.4*0.4) = ~0.6928 per tick when legacy speed limiting was used. It (falsely) assumed 0.4 to be the maximum movement, but that's only with the new speed limiting system.
