### ISSUE TITLE
Cart station bug

### ISSUE THREAD

**Issue by ryando123** [bergerhealer/TrainCarts#250]
##### Spigot version: 1.12.2-R0.1-SNAPSHOT

<hr>

#### Steps to reproduce: Place a cart station and spawn a train that is longer than 1 car

![image](https://user-images.githubusercontent.com/25272264/52299441-ad83dc80-2985-11e9-868c-3696d317e27d.png)
Below the track here is the sign
[cart]
station

**Comment by herboy8** [comment]
Hi ryando123,

From your screenshot it is not quite clear where your sign is positioned, so maybe this is not the case in your scenario, then feel free to ignore it :)

I think you might not fully understand the difference between a cart station and train station. A cart station (when powered) will stop the first cart on that piece of rail. A train station will stop the middle of the train on that piece of rail. To clarify this I attached an example:
![train example](https://user-images.githubusercontent.com/4084628/52372964-cc53a300-2a59-11e9-977d-075deff72605.png)

Hope this helps! Otherwise, you might considering updating your server and the plugins to the latest version and see if that helps, since these work fine for me.

**Comment by ryando123** [comment]
Other servers are having the same issue...
Maybe you dont have the latest builds

**Comment by ryando123** [comment]
The sign below the track is a cart station and it is clear that it stops in the middle, I know the difference between them. I’m also giving support 🤔

**Comment by herboy8** [comment]
Sorry, didn't know that, just tried to help.
I do use the latest version and not having this issue.

**Comment by bbayu123** [comment]
Confirmed to be issue of TC build 445, caused by updating of new station logic

**Comment by weeryan17** [comment]
@herboy8 their are dev versions of train carts that a lot of people use

**Comment by ryando123** [comment]
The cart station doesn't work with the latest build.

**Comment by weeryan17** [comment]
My bad in the last pr. this one should actually work (i tested it)

**Comment by ryando123** [comment]
Yep it works now, thanks!
