### ISSUE TITLE
Trains stopping/crashing into other trains when far away or chunks are unloaded.

### ISSUE THREAD

**Issue by TREGuy365** [bergerhealer/TrainCarts#259]
##### Spigot version: 1.13.1

<hr>

**Comment by bbayu123** [comment]
You need the train property keepChunksLoaded set to true.

(Related to #217)

**Comment by TREGuy365** [comment]
The trains are always being spawned and despawned. how do i set this to all trains? a command block?

**Comment by TREGuy365** [comment]
i have a metro network on a server.

**Comment by TREGuy365** [comment]
and how do i do this?

**Comment by bbayu123** [comment]
can you tell me how your trains are spawned, and what is the syntax used to spawn the train(s)?

**Comment by TREGuy365** [comment]
[train]
spawn 0:55 0.5
mmmmmmmmmmmmmm

**Comment by TREGuy365** [comment]
Then they are destroyed with 
[+cart]
destroy

**Comment by TREGuy365** [comment]
is there a sign command that changes properties??

**Comment by bbayu123** [comment]
You need to go into your server folder, then navigate into /plugins/Train_Carts/DefaultTrainProperties.yml
Change the following:
```yaml
spawner:
    keepChunksLoaded: true
```

**Comment by TREGuy365** [comment]
hello?

**Comment by mio9** [comment]
if you're not feeling safe to edit DefaultTrainProperties.yml , alternatively, you can add a property sign that writes
```
[train]
property
loadchunks
true
```
on the way the newly spawn train will pass through.   
p.s. If you wish to make the sign work no matter there is redstone signal or not, replace `[train]` with [+train]`  , for more information about action signs, feel free to check the wiki out:
 - **Property sign** https://minecraft.gamepedia.com/Custom_servers/Bukkit/TrainCarts/Signs/Property
 - **Action signs**: https://minecraft.gamepedia.com/Custom_servers/Bukkit/TrainCarts/Signs

----
Please consider testing the possible solutions out responding to this issue with the result, whether it works or not, so that we could understand the latest situation and help you out base on that

**Comment by TREGuy365** [comment]
thanks!
