### ISSUE TITLE
Spawner issues

### ISSUE THREAD

**Issue by TREGuy365** [bergerhealer/TrainCarts#278]
##### Spigot version: Spigot 1.13.2

<hr>

**Comment by bergerkiller** [comment]
Can you try to reproduce this again with the latest development builds, just in case the issue is already fixed? There were quite a lot of changes with the underlying system of the automatic spawner sign since 1.13.2.

https://ci.mg-dev.eu/job/BKCommonLib/590/
https://ci.mg-dev.eu/job/TrainCarts/486/

**Comment by TREGuy365** [comment]
umm im on an aternos server and i use linux so i dont really know how to do that

**Comment by bergerkiller** [comment]
Hmm alright, Ill do some testing later today to make sure it does work in latest dev. I plan to do a new release hopefully today, otherwise later this week.

**Comment by TREGuy365** [comment]
Yay TC 1.14.4!!!

**Comment by bergerkiller** [comment]
I've done some testing and it appears to function fine. What I've done to verify it:
- Spawn sign spawning every minute with launch speed
- Destroy sign destroys the minecart again
- Halfway is a detector rail triggering a command block to broadcast a message
- Below the spawn sign is a property keepchunksloaded sign, so the train makes it

I went very far away and let it run, and it continued broadcasting the message. When I removed the keep chunks loaded property sign, trains would stop at the spawn sign, but they did continue spawning.

So it looks like this issue is resolved.

**Comment by TREGuy365** [comment]
Hey bergerkiller i found a solution

**Comment by TREGuy365** [comment]
put a couple carts in a hole and add the property keepchunksloaded to them and the the spawn sign worked

**Comment by bergerkiller** [comment]
Yeah thats a valid workaround that works too. In the newer version this bug is apparently fixed though, but just in case it isn't, you got your workaround.
