### ISSUE TITLE
Issue with eject signs

### ISSUE THREAD

**Issue by MrKittle** [bergerhealer/TrainCarts#282]
##### Spigot version: 1.12.2-R0.1-SNAPSHOT

<hr>

#### Problem or bug: Eject signs do not work correctly. I defined in DefaultTrainProperties an exitOffset like this: x:-2 y:1 z:0 and the players leave the train 1 block up and 2 blocks on the right to reach the station plateform. At certain stations I placed an eject sign to automatically eject players. Whatever eject sign I place, players are ejected always on the left side of the train or at their cart location. Never on the right even if I put a positive or negative coordinate.  In the Wiki it says that X=(forward/backward) Y=(Up/Down) and Z=(Left/Right). I thought that placing an eject sign wihout the third line would eject players by using the exit offset parameters defined in DefaultTrainProperties.yml but it doesn't. It occures only with eject signs on my train network. If players leave the train by themselves, it respects the parameters defined  in DefaultTrainProperties.yml.
Yesterday I noticed that trains were bounced back over a switcher sign like: "[train] switcher minecart". As the train was bounced back it was normal that the eject event occures on the wrong side but now that the switcher signs work well, the eject event still not work with eject signs.
#### Expected behaviour:
I expected that when players leave the train by themselves or are ejected by a sign, both eject players at the same location because similar coordinates are defined on the sign and in the YML file.

#### Steps to reproduce:

With luck, try just to place an eject sign with or without coordinates to eject players, then define coordinates in DefaultTrainProperties.yml and try to leave a train yourself and  also by an eject sign. I hope you'll succeed in reproducing that issue.

**Comment by bergerkiller** [comment]
Can it be that you are ejecting players when the train is stopped on a station? My guess is that when at standstill the forward direction is less obvious, and even reverses, causing what would be relative right to become relative left instead.

Can you check:
- Whether the same thing happens when you define a custom exit offset in the attachment editor for the seat attachment? Its under appearance (first menu slot)
- Whether the same issue also occurs when you eject the train while it is still moving (if you used a station)

**Comment by bergerkiller** [comment]
Okay the eject sign is indeed bugged. It calls this function when not specifying an offset yourself, which appears wrong as it overrides some stuff it would use otherwise.
![ScreenShot_2019-08-01 22-12-37](https://user-images.githubusercontent.com/957601/62324302-7c561600-b4a9-11e9-92cb-a35f07d8f377.png)

**Comment by bergerkiller** [comment]
See if this changes anything for you. https://ci.mg-dev.eu/job/TrainCarts/493/

**Comment by MrKittle** [comment]
Hello,
I tested the version in the link above and it resolved the issue :-)
Concerning the trains bouncing back over a switcher sign, I just noticed that it happens only when there is more than one player riding the train. I will try tomorrow to replace the signs and test with another player to see if it occures again.

I thank you very much again for the fixing :-)

Cordially,
Mr_Kittle.

**Comment by bbayu123** [comment]
Please open a new issue ticket if you want to report your issue regarding switcher signs.
