### ISSUE TITLE
Train Chest pickup and spawn not correctly updating the item

### ISSUE THREAD

**Issue by bbayu123** [bergerhealer/TrainCarts#292]
##### Spigot version: b1573-j

<hr>

#### Problem or bug:
In Survival
1. Train Chest does not become empty after placing down a train.
2. Train Chest does not stop players from picking up a train after it has a train in it.
3. Pick-up and drop-off does not correctly update the item name, unlike creating a chest with a command (Expected `Traincarts Chest (Empty)`, `Traincarts Chest (TrainName)`, got `Traincarts Chest`)

**Comment by bergerkiller** [comment]
Oh I never intended for the chest item to be used in survival mode, I can see the complaints in that case. Should behavior be different when in survival vs creative mode? Or perhaps it needs a different command for a 'survival' chest?

**Comment by bbayu123** [comment]
@Wortho27 see above.

**Comment by bbayu123** [comment]
![image](https://user-images.githubusercontent.com/26726381/69018914-5de73c80-09fe-11ea-8e4f-54acbf5baf61.png)
@bergerkiller

**Comment by CuzImKatze** [comment]
TCCoaster Version: Last Build
TrainCarts v1.14.4-v2-SNAPSHOT (build:552)
BkcommonLib v1.14.4-v2-SNAPSHOT (build:657)

Bugs:
 https://streamable.com/18oga
https://streamable.com/wqc92
https://streamable.com/xrgbu

**Comment by bergerkiller** [comment]
The name (point 3) is a little difficult to do, because the original saved train name that a train on the track represents isnt kept around. I could use the name of the train, but idk how useful that is. ('train12')

I guess being able to lock a chest so it cannot pick up another train when clicking can be useful also in creative. I could make it a tag set when giving the chest item, which is also set when giving a survival chest in the future.

When I got time Ill look at implementing something basic for survival use. Only thing is, it feels weird to require commands to obtain such an item. Normally this is done through a crafting recipe. If there's a better way to do this, I'm open for suggestions.

**Comment by bbayu123** [comment]
I... think this has been implemented using the TrainNameFormat property and it... should be working... so let's just close this shall we.
