### ISSUE TITLE
Train carts Animation bug

### ISSUE THREAD

**Issue by Disneykid93** [bergerhealer/TrainCarts#309]
##### Spigot version: Paper version git-Paper-160 (MC: 1.14.4)

<hr>

#### Steps to reproduce: Watch video to see what is going on.

https://www.youtube.com/watch?v=7Gk-b3Dys78&feature=youtu.be

**Comment by bergerkiller** [comment]
Looks like the yaw compensation is happening at an angle it really shouldn't. Yaw compensation is done to make yaw rotations (relative to the world) smoother by using the entity yaw. The rotation of the armorstand head in your case has both yaw and pitch information, and as a result this compensation is making things worse.

Thanks for the clear example and configured positions, I'll see this weekend what I can do to fix this.

**Comment by Disneykid93** [comment]
Your welcome Berger. If i can get the errors in console if there are any i will post it so you can see what is going on.

**Comment by bergerkiller** [comment]
The logic it currently uses to deduce the change in yaw from one quaternion to another is incorrect. It detects a change in yaw because the base rotation has a 90 degree pitch. So to go from one to another, you indeed multiply with a change in yaw, but that yaw is not relative to world coordinates.

I'm working on fixing this

**Comment by Disneykid93** [comment]
Ok Thanks Berger.

**Comment by bergerkiller** [comment]
It's a small commit, most time was spent verifying it. These changes should stop the weird yaw corrections when they shouldnt happen. When the pitch was set to 45 degrees however, they still occurred, but that is a more ambiguous case because there is actual rotation along Y then.

https://github.com/bergerhealer/TrainCarts/commit/f7965899813c9fc98294c600c7a4a9453875902e

https://ci.mg-dev.eu/job/TrainCarts/535/
