### ISSUE TITLE
Minecarts can be pushed into blocks regardless of collision settings

### ISSUE THREAD

**Issue by JLyne** [bergerhealer/TrainCarts#319]
##### Spigot version: Paper #232 1.14.4

<hr>

#### Problem or bug: 
If a minecart is up against a block, while on a rail, a player walking into it seems to often cause the minecart to go inside the block. This seems to happen regardless of the train's block collision setting, with it being reliably reproducible with block collision set to DEFAULT.

Trying this without train carts will result in the minecart simply not moving. It is also reproducible for me with no other plugins installed.

![image](https://user-images.githubusercontent.com/4615316/69915337-b9c1b480-1445-11ea-8b02-fad57656924f.png)

#### Expected behaviour: 
Minecarts against blocks being pushed by players don't move into blocks, unless the collision settings permit it.

#### Steps to reproduce: 
1. Place a rail against a block
2. Put minecart on rail
3. Push minecart in direction of block

**Comment by bbayu123** [comment]
Hi, can you check to see whether the issue still occurs in the latest snapshots of bk and tc? Please write down the build numbers used if the issue still occurs, thanks.

**Comment by Vlader97** [comment]
I have this problem too. The issue still occurs in the latest version.
BkCommonLib version: 1.15.2-v1
TrainCarts version: 1.15.2-v1
Paper version: 1.15.2 build-105

**Comment by bbayu123** [comment]
To be fair, even vanilla minecarts clip into blocks on the default setting without traincarts, so I'm not really sure if this is a TC bug or a Minecraft bug... Will let Berger figure it out though.

If you can provide a video showing how exactly it can be reproduced, with the train info shown in the video, that would definitely help

**Comment by bergerkiller** [comment]
No need for a video honestly, I know the problem exists and its super easy to reproduce (just stand against a minecart while its leaning against a block)

**Comment by bbayu123** [comment]
Oh really, it's that easy to reproduce? Maybe I just don't use minecarts that often lol.

**Comment by Vlader97** [comment]
I tested on vanilla 1.15.2 and on clean Paper 1.15.2 build-112 and in both cases the minecart not go inside the block. 
After I add plugin, minecart go inside the block but only minecarts that I newly place after added plugin. But the interesting is that minecarts that were in the world before the plugin was added, working as in vanilla even with the plugin. Plugin config is default.

**Comment by bergerkiller** [comment]
Yup, vanilla and traincarts minecarts can co-exist, unless you change that in the config.yml

**Comment by bergerkiller** [comment]
This issue stems from BKCommonLib's movement physics itself, it is not traincarts cancelling/allowing the collision. Nasty issue, hopefully I can debug it, because that streaming VoxelShape code is a nightmare

**Comment by bergerkiller** [comment]
Alright so many, many hours later, I come here with an answer and a solution.

What was happening was that, as a player bumps a minecart, he changes the velocity of the minecart directly. This velocity is set to a value irrespective of what the movement direction on the rails is. As a result, when you bump it ever so slightly from the side, the minecart is technically pushed sideways on the rails. This triggers the 'curved track' behavior, causing the minecart to treat the straight rail piece as a 45-angle bend, going into the block, and then the glitch is complete.

The solution is rather straightforward: Ive added a handler so that this bumping can be overrided in the controller in BKCommonLib, implemented by Traincarts to bump the minecart without violating the current rail's movement vector rules. As an added bonus, you can now push minecarts up/down vertically as well.

https://github.com/bergerhealer/BKCommonLib/commit/119698211d911fc08950c0a861972df117bcb170
https://github.com/bergerhealer/TrainCarts/commit/d53faea05b8263c026f88a5e99a3170b19bbb723

https://ci.mg-dev.eu/job/BKCommonLib/771/
https://ci.mg-dev.eu/job/TrainCarts/623/
(Update both)

Let me know if any problems persist, or that it's all fixed, then I can close this issue.

**Comment by JLyne** [comment]
Tried it out just now and seems all fixed.

Thanks for looking into it.
