### ISSUE TITLE
Negitive animation speed causes negitive delay

### ISSUE THREAD

**Issue by weeryan17** [bergerhealer/TrainCarts#339]
##### Spigot version: 1.15.2

<hr>

#### Problem or bug:
When using the animation sign the delay is affected by the speed. [This can be seen on line 198 of the AnimationOptions class](https://github.com/bergerhealer/TrainCarts/blob/master/src/main/java/com/bergerkiller/bukkit/tc/attachments/animation/AnimationOptions.java#L198). [This method is called every time an animation is played, and the network controller is present](https://github.com/bergerhealer/TrainCarts/blob/4c388d703ccf9684acb620ce4bedfd985ce9fe1e/src/main/java/com/bergerkiller/bukkit/tc/controller/MinecartMember.java#L2288). If there is a negative speed the delay will most likely be set to a negative value and therefor play instantly. Ideally the delay should ignore speed as most people will want the speed to only affect the main animation.

#### Expected behaviour:
Animations delay ignore the speed when a delay is specified via a sign, or command.

#### Steps to reproduce:
Play an animation with a negative speed and a positive delay via a sign or command.

**Comment by bbayu123** [comment]
https://github.com/bergerhealer/TrainCarts/blob/4c388d703ccf9684acb620ce4bedfd985ce9fe1e/src/main/java/com/bergerkiller/bukkit/tc/attachments/animation/AnimationOptions.java#L198
@bergerkiller Suggested change: `this.setDelay(this.getDelay() + options.getDelay()); `
I think the speed factor there is a refractoring error.

**Comment by bergerkiller** [comment]
This is the apply function, which takes existing options and 'applies' new options to it. In that case the original delay specified for the animation must be kept, otherwise weird things happen. The idea is that the animation-defined delay can be used as a phase during looped animations, when you have multiple of them running in sync

**Comment by bbayu123** [comment]
So... what happens when a brand new animation with negative speed and positive delay is applied? Some people can't get the delay to work at all in negative speed scenarios...

**Comment by bergerkiller** [comment]
The idea of a negative delay is primarily important in looped animations. Basically, it changes the phase of the animation in the other direction. When not looped I don't think the behavior is very clearly defined.

I'm currently busy with some ASM stuff, so I can't really look at this right now, but feel free to define how the behavior should work

**Comment by bbayu123** [comment]
Pretty sure berger isn't understanding this issue (at the time he was commenting on this).
Negative speed causes negative delay, **which should not happen**.
Animations playing at a negative speed will not receive any delay even though explicitly specified because the code that handles the calculation of the delay makes it negative, which means all animations played at negative speed will play instantly, COMPLETELY ignoring the delay.
He does understand now, and apparently he's slow at clearing non-urgent issues.

**Comment by bergerkiller** [comment]
Ive made some changes:
https://github.com/bergerhealer/TrainCarts/commit/f02a12e58d265e8d1fe0d22ea059485e9a447825
https://github.com/bergerhealer/TrainCarts/commit/56de80b61de2084748dfa545b386008696fe4701

Delays put on the sign are no longer affected by speed, now. Let me know if issues persist.

**Comment by bergerkiller** [comment]
Have these changes helped or is the delay still wrong?

**Comment by bbayu123** [comment]
@weeryan17 Update on this 3-month-old issue ticket?

**Comment by weeryan17** [comment]
I have no idea. I made this issue on behalf of LookItsBenji as I was the one who investigated the issue with the code. You'll need to talk to them to find out if its fine now.

**Comment by bbayu123** [comment]
@OfficialBenjy ima close this if you don't respond

**Comment by weeryan17** [comment]
According to Benjy in the discord server he now uses a custom sign, for now I guess we can assume this is fixed.
