### ISSUE TITLE
Suggestion: Keep vanilla behavior for single carts not spawned using spawner

### ISSUE THREAD

**Issue by bindingflare** [bergerhealer/TrainCarts#348]
<hr>

#### ~~Problem or bug~~ Enhancement:
Cart behavior is at best similar to vanilla carts and not equal. This suggestion changes only carts placed by users (without using signs) and carts which have not been connected to other carts at least once. Such carts will remain as vanilla carts and not be modified by this plugin.

#### Expected behaviour:
Single carts placed by user will remain as vanilla carts until it first connected to another cart. To produce a train with a single cart signs can be used or a workaround (create a train of 2 carts then remove 1 cart).

#### ~~Steps to reproduce~~ Benefits:
There will be no way a problem with any vanilla farm that uses minecarts fails to work on any version of Minecraft due to this plugin if this change is added. All such issues will be resolved as "use vanilla carts please".

**Comment by bergerkiller** [comment]
what is wrong with the current train.place.traincart permission so people can place down vanilla carts if they choose? (if they lack this perm they place vanilla minecarts and they stay vanilla)

**Comment by bindingflare** [comment]
Tbh, i have used tc for 2 years and i did not know the permission existed. Thats a bummer for me. My bad.

However i still consider this idea to be a possible enhancement, since the rules that govern tc trains and vanilla carts is simple (ofc i know very little of internal code to know if in practice it is simple to implement) and plug-and-play (which is users-like-me friendly). Another side effect of this change is also the minecart chests in mineshafts as this rule also applies to naturally spawned entities meaning less checks for them. The permissions seems kinda rigid as i would need to constantly op and deop myself to enjoy both worlds.

Thanks for the comment tho! Actually helps my survival server. You can close this issue if you prefer.

**Comment by bergerkiller** [comment]
I'll keep it open in case it garners interest, as it's not impossible to do. It's just a bit out of the ordinary.

How I see it:
1. Placing down minecarts places vanilla minecarts
2. When two vanilla minecarts (or a minecart and traincart) collide, it swaps the entity out with a Traincart
3. They now form a train. When they disconnect/turn back into one minecart, they continue being a traincart (no swapping back)

This can be achieved by handling the vehicle collision event, but it might be slightly buggy. Of course, you can use permissions so that players normally place vanilla minecarts rather than traincarts minecarts. And if you need a train, I believe you can also use
`/train chest m`
To get a chest item that places traincarts minecarts.

**Comment by weeryan17** [comment]
While I do see how this could be useful it should defiantly not be a default feature. Traincarts carts do a lot more then just mimic vanilla even when they're alone. Main one of those features being attachments.

**Comment by bergerkiller** [comment]
Yup, which is why I also get why people would want to spawn vanilla minecarts alongside traincarts minecarts, especially for timing-sensitive redstone contraptions and the like. The physics are wildly different nowadays.

**Comment by FireController1847** [comment]
I have a suggestion: Instead of basing this on how the carts are made, why not just create a toggle? Allow people to toggle TrainCarts on and off on an individual basis, kind of like godmode on essentials or various other plugins. Then we don't even need to worry about advanced detection or whatnot, it'd be basically like checking for the permission but in a far more user-friendly manner. Suggested commands: `/traincarts on` and `/traincarts off` and/or `/traincarts toggle`

**Comment by bergerkiller** [comment]
Technically you could just never give people the train.place.traincart permission, and just require the use of `/train chest m` to place down traincarts minecarts. Then the separation is quite clear without having to change permissions on the fly

Im hesitant to mix vanilla and traincarts, because:
- A minecart not activating signs and being unselectable might seem like a traincarts bug
- Visually not much changes, and people will find it hard to differentiate the two type of carts
- People might accidentally turn vanilla minecarts into traincarts on a large scale, breaking things

**Comment by FireController1847** [comment]
I suppose that makes sense, I could see why it could become a maintenance nightmare. Oh well, I'm glad I at least know this permission exists :sweat_smile:

**Comment by bbayu123** [comment]
Removing `keep in open` tag, closing issue. For more information, refer to the wiki page on [Vanilla Minecarts](https://wiki.traincarts.net/p/TrainCarts/VanillaMinecarts).
