### ISSUE TITLE
Players get stuck in Minecarts and can't get out

### ISSUE THREAD

**Issue by TREGuy365** [bergerhealer/TrainCarts#349]
##### Spigot version: Paper 1.15.2

<hr>

**Comment by weeryan17** [comment]
This sounds like one of two issues
1. A plugin conflict. If it is this problem we'll need a list of all plugins you have.
2. You turned playexit off somewhere. weather that be in the DefaultProperties.yml file or on the train its self.

**Comment by bergerkiller** [comment]
Were there any errors in the server log prior to when this happened? Sneak should allow players to exit yes, providing the playerexit property isn't set to false/deny.

Could you check whether this issue still exists with the latest dev builds of traincarts and bkcommonlib, since it's easily reproducible on your end? A plugin conflict like weeryan mentioned could be the case (if another plugin disallows ejecting)

https://ci.mg-dev.eu/job/BKCommonLib/763/
https://ci.mg-dev.eu/job/TrainCarts/616/

**Comment by TREGuy365** [comment]
The only plugins I'm using at the moment are SignLink, BKcommonLib, TrainCarts and Worldedit.

**Comment by bbayu123** [comment]
Can I assume that the builds linked have fixed the issue?

**Comment by bbayu123** [comment]
Closing, for now. Reopen if you still have this issue.
