### ISSUE TITLE
1.15.2 Trains spawing wrong

### ISSUE THREAD

**Issue by Thisie** [bergerhealer/TrainCarts#365]
##### Spigot version: 1.15.2

<hr>

#### Problem or bug:
Trains spawing wrong since updating to 1.15 for SmoothCoasters. I can't get them normal.

![](https://cdn.discordapp.com/attachments/417019799365746690/716406573966295091/unknown.png)

#### Steps to reproduce:
Make a train, save it and spawn with a spawn sign.

**Comment by bbayu123** [comment]
Can you check if updating to build 654 fixes it?

**Comment by Thisie** [comment]
I tried build 655 too but it's not fixed yet.

**Comment by bbayu123** [comment]
Well, to be fair, I have no idea why that image is wrong as I have no comparison, so I don't see the issue here.

**Comment by Thisie** [comment]
This is how they should look like.
![image](https://user-images.githubusercontent.com/24739624/84940106-a6272400-b0df-11ea-939e-7d1d98ae0008.png)

**Comment by bergerkiller** [comment]
Is this issue still happening? I think the problem is that carts part of a train randomly flip (rather than that the entire train is flipped). It's not simply that when saving the carts had an incorrect orientation? It was fixed that a standing-still train had random orientations, and if not made moving, saving the train again caused random flipping.

If you saved the train while it was moving forward, then that is the not the issue at hand here

**Comment by Thisie** [comment]
I fixed it using :right or :left after train ([train:right] etc.)
