### ISSUE TITLE
Trains going wrong on Transfertrack

### ISSUE THREAD

**Issue by Thisie** [bergerhealer/TrainCarts#375]
##### Spigot version: 1.14.4

<hr>
[Image](https://user-images.githubusercontent.com/24739624/85578517-68c01a80-b63a-11ea-86b5-871d716c744f.png)
[GIF](https://i.gyazo.com/7c980945f406d6a52f71f2ac27ca2e62.gif)

#### Problem or bug:
When making two track animations, the train is glitching and will not be able to ride anymore.

#### Expected behaviour:
The train rides over the track that is linked with each other.

#### Steps to reproduce:
Make two animated tracks and connect them with one single node. (one at a time)

**Comment by bergerkiller** [comment]
Just for my information: I see two sections of track switching in and out of place. Do both sections use the same configured rail block? Because that might be a big reason why this happens. The train then tries to turn the Rail Block back into a path, and picks the 'wrong' type of path to do so, causing the train to teleport like this.

**Comment by bergerkiller** [comment]
While this is now a month old, if the issue still exists, I think having the coaster csv file of this section can be helpful, as I can't exactly reproduce it at the moment.

**Comment by Thisie** [comment]
I have made that every tracksection has his own rail block, but the problem is still there.

**Comment by Thisie** [comment]
[track dvh.zip](https://github.com/bergerhealer/TrainCarts/files/4967051/track.dvh.zip)
Here are the tracks

**Comment by bergerkiller** [comment]
Ive been doing some testing, but so far it appears to behave normally. The only glitch I've managed to cause is doing animations while the train is on the junction, because the rail tracker logic thinks the end of the path is somewhere different than it really is. It caused the cart to weirdly deform, and when the animation was finished, it would snap back into the correct position.

But passing over it worked fine.

I used carts with a length of 1.5 and wheel distance of 1.4. (4 carts) I did remove all the objects, as it was lagging my client a little bit on 1.16.1
![ScreenShot_2020-07-23 23-32-10](https://user-images.githubusercontent.com/957601/88340796-bc5a7c80-cd3c-11ea-9b47-d01811ad68ca.png)

Is there more information that could help me?

**Comment by Thisie** [comment]
How have you configured the rail blocks? I don't get it.

**Comment by bergerkiller** [comment]
The way you had them configured at the time. There's two sections each with their own rail blocks, where I put the signs

**Comment by Thisie** [comment]
Updated server version and TC, TCC & BKCommonLib. Works fine now!

**Comment by bergerkiller** [comment]
Oh good to hear! Glad it was a version issue :)
