### ISSUE TITLE
Cannot Transfer Items To/From Chests or Craft

### ISSUE THREAD

**Issue by David1544** [bergerhealer/TrainCarts#376]
##### Spigot version:  Paper-371 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

<hr>

#### Problem or bug: 
An error is given when trying to move items to/from a chest minecart
[Pastebin](https://pastebin.com/wcKTNMis)

#### Expected behaviour: 
Items to transfer

#### Steps to reproduce: 
Create transfer signs and chests, attempt to move items in between, see that they don't transfer.

**Comment by bergerkiller** [comment]
I forgot to post a message here, this has since been fixed. There were some method changes, among which https://github.com/bergerhealer/BKCommonLib/commit/0a794b4766614873a29bf0fec0f3bae0fef06396

The test setup of mine, which tests transfer + craft, works fine now. I can confirm that it did not work in the past.
