### ISSUE TITLE
Hopper fill rate is slow

### ISSUE THREAD

**Issue by Coconutreactor** [bergerhealer/TrainCarts#398]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): BKCommonLib-1.16.3-v1
- TrainCarts Version (`/train version`):  TrainCarts-1.16.3-v1
- Server Type and Version (`/version`): Paper 1.16.3

----
### Description
Hopper minecarts aren't taking in items at the same rate as vanilla (20 blocks per tick?)

### Expected behaviour
What do you expect TrainCarts to do?
Items are taken in at the same rate as vanilla

### Actual behaviour
What is TrainCarts doing instead?
The speed is much slower, at around 6-7 items per tick

### Steps to reproduce
Please list the steps to take, in order to reproduce the bug.
Unfortunately, I only noticed when I started to make a super smelter on my server and noticed it being much less efficient compared to my single player save, but basically:

1. Put a hopper minecart below a chest
2. Put items inside the chest
3. It should be obvious that it is not taking in items at the correct speed.

### Additional Information
Any additional information we should know of?

Interestingly enough, since my server has Multiverse installed, some worlds seem to have the hoppers function exactly like vanilla, but that is only 1 out of 4 total worlds in my server that actually works.

**Comment by Coconutreactor** [comment]
#350 seems to be talking about the same issue.

**Comment by bergerkiller** [comment]
I can confirm this (chest above hopper, vanilla differs from TC) but I can't explain it. A function Im calling returns a value indicating there were no items transferred, despite actually transferring items. Very puzzling, but hopefully I can figure this out.

**Comment by Andre601** [comment]
I believe this is a setting or similar of Spigot as it is somewhat known that they change some hopper behaviours.
If I recall correctly can you even set Spigot to transfer Items in batches of multiple items instead of a single one per timeframe.

So this is a Spigot *issue* in this case and would require to somehow override the hopper minecart behaviour.

**Comment by bergerkiller** [comment]
This is unbelievable. I hate this.

So what's happening is that on Vanilla, it's actually bugged.

This is the code:
```
            if (blockposition.equals(this.f)) {
                --this.e;
            } else {
                this.setCooldown(0);
            }

            if (!this.C()) {
                this.setCooldown(0);
                if (this.B()) {
                    this.setCooldown(4);
                    this.update();
                }
            }
```

You would think this looks about right. If the current block position of the entity is different, then reset the cooldown to 0 instantly, otherwise decrement the cooldown every tick. In C() it checks if its on cooldown, if not, it sucks in items (B()) and when this succeeds, it sets a cooldown of 4 ticks. This is meant to slow down the rate of the hopper I guess?

Except this doesn't happen. That code of checking if the block position changes is actually broken! The f variable is final and is always set to ZERO. Meaning that, if your hopper is at exactly 0/0/0, it'll transfer items at the expected every 4 ticks. But if it's not, it will transfer every tick.

Since traincarts implemented this correctly, and handles onBlockChange to reset the timer, it well. Works. But apparently people are now used to this idea that hopper minecarts transfer every tick, but this is clearly broken code!

https://cdn.discordapp.com/attachments/417019799365746690/768602115303538688/2020-10-22_00-29-11.mp4

**Comment by bergerkiller** [comment]
I'll just yeet out all this cooldown code because it clearly does nothing on Vanilla Minecraft. It might be worth using so you can save some performance by setting a cooldown when items are NOT transferred. This is done by replacing
`if (this.B()) {`
with
`if (!this.B()) {`

But then there might be other quirks of the hopper minecart not responding to items going into the chest above as quickly as people expect. So whatever, I'll just disable this cooldown code entirely.

**Comment by bergerkiller** [comment]
https://github.com/bergerhealer/TrainCarts/commit/6d033a31476c41f992571b6d9e75ed92cf66fe13
https://ci.mg-dev.eu/job/TrainCarts/734/

**Comment by Andre601** [comment]
Weird that this has never be seen as a bug (Not even at Mojang's end... And they MADE this!) and was never reported at all... It would imo be a good idea to consider making a bug report...

But I would also assume that it is now considered an "expected behaviour" since the minecart *only* works when it is at exactly 0, 0, 0

**Comment by bergerkiller** [comment]
https://bugs.mojang.com/browse/MC-65029 so it was reported

**Comment by Coconutreactor** [comment]
Yep, seems to be fixed in the newest snapshot.
