### ISSUE TITLE
cant accelerated,get stuck,detecter does not seem to be very sensitive.

### ISSUE THREAD

**Issue by HoneyAlloy** [bergerhealer/TrainCarts#428]
## Info
Please provide the following information:

- 1.17 BKCommonLib 1.1105
- 1.17 TrainCarts 1.941
- 1.17.1-180 paper

----
### Description
1. The train can decelerate but cannot accelerate. I set the launch speed to 0 and the train stopped well. But when I set it to 5, 10, 100, the speed of the train did not change.
2. Sometimes multiple trains stay at the same station and get stuck, making the creak when the train is moving. Other trains will depart normally after arriving at the station, just like transparent. But it can still be knocked out by hand. (I enabled keepChunksLoaded).
3. It may be related to the second article. The detecter does not seem to be very sensitive. Sometimes the train is already on the track, but the light does not turn on.

### Expected behaviour
It can be accelerated, will not get stuck, and the detector will be more sensitive.

### Actual behaviour
up.

### Steps to reproduce
up.
### Additional Information
maybe none.

**Comment by bbayu123** [comment]
1. "cannot accelerate" You need to change the train's maxspeed property in order to have it accelerate beyond what is normally acceptable. If you want to go higher than 5, then you must also change the value in the config, since that acts as a hard cap.
2. What do you mean by "stuck"? What does it look like? Trains don't "creak", so that also doesn't make sense.
3. If you set up your detectors incorrectly, they won't detect the region you want. Without knowing more information, we cannot help you with that.

**Comment by HoneyAlloy** [comment]
> 1. “无法加速” 您需要更改火车的 maxspeed 属性，以使其加速超出通常可接受的范围。如果您想高于 5，那么您还必须更改配置中的值，因为它充当硬上限。
> 2. 你说的“卡住”是什么意思？它是什么样子的？火车不会“吱吱作响”，所以这也没有意义。
> 3. 如果您错误地设置检测器，它们将无法检测到您想要的区域。在不了解更多信息的情况下，我们无法为您提供帮助。

It means that several trains overlapped and stuck at the station motionless, but they kept making sounds like they were moving. This caused my detector to detect problems, and the detector runs normally under normal circumstances.

**Comment by bbayu123** [comment]
Well, firstly, a video would help, since I still cannot grasp the problem that you're having. Also, check for any errors that may have appeared in the console. If you're using a 1.17.1 server, I also suggest upgrading to the latest development build, as I think some critical issue was fixed there. 中文OK, but I tend to respond in English so that others also know what is happening.

**Comment by HoneyAlloy** [comment]
like this(那我也英语好了)
![2021-08-25 11-44-13](https://user-images.githubusercontent.com/79710384/130795635-71b437ea-97e6-408e-a444-e9d818ba3b05.gif)
Can only send 10MB...

**Comment by HoneyAlloy** [comment]
I set the maximum speed, but the problem came again. When I set it to 1, the train slowed down and then changed back to the original speed.

**Comment by bbayu123** [comment]
Closing issue, stale - not enough information.
